# Generated by Django 4.1.5 on 2026-01-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("unit_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("unit_name", models.CharField(max_length=32)),
                ("company_id", models.BigIntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=64, null=True)),
                ("short_name", models.CharField(blank=True, max_length=10, null=True)),
                ("unit_logo", models.BinaryField(blank=True, null=True)),
                ("unit_logo_path", models.CharField(blank=True, max_length=64, null=True)),
                ("authorized_sign", models.BinaryField(blank=True, null=True)),
                ("authorized_sign_path", models.CharField(blank=True, max_length=64, null=True)),
                ("bang_unit_name", models.CharField(blank=True, max_length=50, null=True)),
                ("bang_address", models.CharField(blank=True, max_length=64, null=True)),
                ("remarks", models.CharField(blank=True, max_length=32, null=True)),
                ("updated_by", models.BigIntegerField(blank=True, null=True)),
                ("updated_date", models.DateField(blank=True, null=True)),
                ("created_by", models.BigIntegerField()),
                ("created_date", models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "db_table": "UNIT",
                "managed": True,
            },
        ),
    ]
