# Generated by Django 4.1.5 on 2026-01-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='unit_id',
        ),
    ]
