# Generated by Django 4.1.5 on 2026-01-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_department_unit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='bangla_department_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='show_priority',
        ),
        migrations.AddField(
            model_name='department',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
