# Generated by Django 4.1.5 on 2026-01-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_department_bangla_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
