# Generated by Django 4.1.5 on 2026-01-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_alter_department_updated_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="created_date",
            new_name="created_at",
        ),
    ]
