# Generated by Django 4.1.5 on 2026-01-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_by',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
