# Generated by Django 4.1.5 on 2026-01-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_department_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='priority',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
