# Generated by Django 4.1.5 on 2026-01-06 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_alter_department_priority"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="updated_date",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="unit",
            old_name="updated_date",
            new_name="updated_at",
        ),
    ]
