# Generated by Django 4.1.5 on 2026-01-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_department_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='authorized_sign',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='authorized_sign_path',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_logo_path',
        ),
        migrations.AddField(
            model_name='unit',
            name='authorized_signature',
            field=models.ImageField(blank=True, null=True, upload_to='company/authorized-signatures/'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='company_id',
            field=models.BigIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/unit-logos/'),
        ),
    ]
