# Generated by Django 4.1.5 on 2026-01-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0012_designation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="designation",
            old_name="id",
            new_name="designation_id",
        ),
    ]
