# Generated by Django 4.1.5 on 2026-01-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_department_is_active_designation_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=64)),
                ('short_name', models.CharField(blank=True, max_length=10, null=True)),
                ('company_name_bang', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.CharField(blank=True, max_length=64, null=True)),
                ('address_bang', models.CharField(blank=True, max_length=64, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/logos/')),
                ('remarks', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'COMPANY',
                'managed': True,
            },
        ),
    ]
