# Generated by Django 4.1.5 on 2026-01-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_company_alter_designation_designation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
