# Generated by Django 4.1.5 on 2026-01-06 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_company_company_phone_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name="unit",
                    old_name="company_id",
                    new_name="company",
                ),
                migrations.AlterField(
                    model_name="unit",
                    name="company",
                    field=models.ForeignKey(
                        db_column="company_id",
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="company.company",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
