# Generated by Django 4.1.5 on 2026-01-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_remove_unit_company_id_unit_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='address_bang',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
