# Generated by Django 4.1.5 on 2026-01-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0020_empcategory_alter_designation_designation_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="EmpCategory"),
            ],
            database_operations=[],
        ),
    ]
