# Generated by Django 4.1.5 on 2026-01-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_remove_empcategory_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=40)),
                ('bang_sec_name', models.CharField(blank=True, max_length=40, null=True)),
                ('remarks', models.CharField(blank=True, max_length=32, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'SECTION',
                'managed': True,
            },
        ),
    ]
