# Generated by Django 4.1.5 on 2026-01-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_section_alter_designation_designation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('floor_name', models.CharField(max_length=40)),
                ('bang_floor_name', models.CharField(blank=True, max_length=40, null=True)),
                ('remarks', models.CharField(blank=True, max_length=32, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Floor',
                'verbose_name_plural': 'Floors',
                'db_table': 'FLOOR',
                'managed': True,
            },
        ),
    ]
