# Generated by Django 4.1.5 on 2026-01-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_floor_alter_designation_designation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='designation_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
