# Generated by Django 4.1.5 on 2026-01-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalaryRuleInfo",
            fields=[
                ("rule_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rule_name", models.CharField(max_length=64)),
                ("rule_basic", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("rule_house_rent", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("rule_medical", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("rule_transport", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("rule_food", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("rule_attd_bonus", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("rule_dearness_allowance", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("attdance_allowance", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("ot_allowance", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("night_bill", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("washing_bill", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("driver_allowance", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("export_allowance", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("deduct_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("rule_status", models.BooleanField(default=True)),
                ("rule_remarks", models.CharField(blank=True, max_length=128, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, blank=True, null=True)),
            ],
            options={
                "db_table": "SALARY_RULE_INFO",
                "managed": True,
                "verbose_name": "Salary Rule Info",
                "verbose_name_plural": "Salary Rule Info",
            },
        ),
    ]
