# Generated by Django 4.1.5 on 2026-01-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaryruleinfo",
            name="attdance_allowance",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="salaryruleinfo",
            name="deduct_amount",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="salaryruleinfo",
            name="driver_allowance",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="salaryruleinfo",
            name="export_allowance",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="salaryruleinfo",
            name="night_bill",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="salaryruleinfo",
            name="ot_allowance",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="salaryruleinfo",
            name="rule_attd_bonus",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="salaryruleinfo",
            name="rule_basic",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="salaryruleinfo",
            name="rule_dearness_allowance",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="salaryruleinfo",
            name="rule_food",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="salaryruleinfo",
            name="rule_house_rent",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="salaryruleinfo",
            name="rule_medical",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="salaryruleinfo",
            name="rule_transport",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="salaryruleinfo",
            name="washing_bill",
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
