# Generated by Django 6.0 on 2026-01-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_update_date_auto_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=30)),
                ('unit_id', models.BigIntegerField(blank=True, null=True)),
                ('short_name', models.CharField(blank=True, max_length=10, null=True)),
                ('show_priority', models.IntegerField(default=0)),
                ('bang_dept_name', models.CharField(blank=True, max_length=30, null=True)),
                ('remarks', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('bangla_department_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'DEPARTMENT',
                'managed': True,
            },
        ),
    ]
