# Generated by Django 4.1.5 on 2026-01-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0009_department"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="Department"),
            ],
            database_operations=[],
        ),
    ]
