# Generated by Django 4.1.5 on 2026-01-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0010_remove_department_state"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="EmpCategory",
                    fields=[
                        ("emp_category_id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("emp_category_name", models.CharField(max_length=64)),
                        ("bang_emp_type_name", models.CharField(blank=True, max_length=64, null=True)),
                        ("position", models.IntegerField(blank=True, null=True)),
                        ("remarks", models.CharField(blank=True, max_length=32, null=True)),
                        ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                        ("updated_by", models.CharField(blank=True, max_length=150, null=True)),
                        ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                    ],
                    options={
                        "verbose_name": "Employee Category",
                        "verbose_name_plural": "Employee Categories",
                        "db_table": "EMP_CATEGORY",
                        "managed": True,
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
