# Generated by Django 4.1.5 on 2026-01-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0011_add_empcategory_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="empcategory",
            old_name="position",
            new_name="priority",
        ),
    ]
