# Generated by Django 4.1.5 on 2026-01-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0012_rename_empcategory_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="SigningOption",
            fields=[
                ("signing_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("signing_name", models.CharField(max_length=64)),
                ("emp_code", models.CharField(max_length=10)),
                ("signing_priority", models.IntegerField(blank=True, null=True)),
                ("signing_for", models.CharField(max_length=32)),
                ("signing_status", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "SIGNING_OPTION",
                "managed": True,
                "verbose_name": "Signing Option",
                "verbose_name_plural": "Signing Options",
            },
        ),
    ]
