# Generated by Django 4.1.5 on 2026-01-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0013_signing_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="signingoption",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name="signingoption",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, blank=True, null=True),
        ),
    ]
