# Generated by Django 4.1.5 on 2026-01-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0014_signing_option_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftInfo",
            fields=[
                ("shift_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("shift_name", models.CharField(max_length=64)),
                ("in_time", models.TimeField()),
                ("allowed_in_time", models.TimeField()),
                ("out_time", models.TimeField()),
                ("allowed_out_time", models.TimeField()),
                ("grace_time", models.IntegerField(blank=True, null=True)),
                ("grace_out", models.IntegerField(blank=True, null=True)),
                ("break_start", models.TimeField(blank=True, null=True)),
                ("break_end", models.TimeField(blank=True, null=True)),
                ("remarks", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, blank=True, null=True)),
            ],
            options={
                "db_table": "SHIFT_INFO",
                "managed": True,
                "verbose_name": "Shift Info",
                "verbose_name_plural": "Shift Info",
            },
        ),
    ]
