# Generated by Django 4.1.5 on 2026-01-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0015_shift_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="emppersonal",
            name="nominee_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="emppersonal",
            name="nominee_relation",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
