# Generated by Django 4.1.5 on 2026-01-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0016_nominee_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="emppersonal",
            name="nominee_name_bang",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
