# Generated by Django 4.1.5 on 2026-01-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0017_nominee_name_bang"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emppersonal",
            options={
                "db_table": "EMP_PERSONAL",
                "managed": True,
                "verbose_name": "Employee Personal",
                "verbose_name_plural": "Employee Personal",
            },
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE EMP_PERSONAL "
                "ADD COLUMN nominee_name VARCHAR(64) NULL, "
                "ADD COLUMN nominee_relation VARCHAR(32) NULL, "
                "ADD COLUMN nominee_name_bang VARCHAR(64) NULL"
            ),
            reverse_sql=(
                "ALTER TABLE EMP_PERSONAL "
                "DROP COLUMN nominee_name_bang, "
                "DROP COLUMN nominee_relation, "
                "DROP COLUMN nominee_name"
            ),
        ),
    ]
